export interface StudentInfo {
  documentNumber: string,
  documentType: string,
  firstName: string,
  lastName: string,
  email: string,
  address: string,
  neighborhood: string,
  personType: string,
  vulnerablePopulation: string,
  gender: string,
  bloodType: string,
  maritalStatus: string,
  socioeconomicStratum: number,
  eps: string,
  institution: string,
  idCity: number,
  idBornPlace: number,
  idDisability: number,
  academicTraining: string,
  idAcademic: number,
  idStudentType: number,
  phoneNumbers: string[]
}
